### ISSUE TITLE
Italian translation issue

### ISSUE THREAD

**Issue by savemosca** [toleda/audio_ALC898#3]
![senza titolo](https://cloud.githubusercontent.com/assets/4923627/2750850/e5e20aa6-c8a1-11e3-97f6-17dd6f957f16.jpg)
Hi, first of all thank for all your job, i have an issue with latest version of your patch, in the prevoius versions names of audio outputs were well traslated in italian language but with 10.9.2 version they are in english and seems like a development name; all works fine but i want to advise you about this little problem.
Thanks.
P.S. I have also tried to reinstall patch but it doesn't work.

**Comment by toleda** [comment]
The script does not touch the localization files.  If you patched an AppleHDA.kext from Software Update, the localization files are not present.  In that case, install the native 10.9 AppleHDA, update and then patch for 898.

**Comment by savemosca** [comment]
i've tried but the result is the same, but if install applehda included in multibeast, names in preferences are correct, where is my error? applehda's in multibeast are patched with your patches...

**Comment by toleda** [comment]
Yes, similar script for this repo and MultiBeast.  As suggested previously, I always use the native Mavericks AppleHDA.kext.  The complete native kext is only available in 10.9 GM.  Software Updates applied to anything but the native AppleHDA.kext will be compromised.   Again, the problem is not the patch, the AppleHDA.kext you apply the patch to is not native and not complete.
